### ISSUE TITLE
ImportError: No module named builtins

### ISSUE THREAD

**Issue by cioma** [xesscorp/KiPart#2]
When running KiPart 0.1.10 using Python 2.7.6 or 2.7.10 the following error is given:
Traceback (most recent call last):
  File "/usr/local/bin/kipart", line 7, in <module>
    from kipart.__main__ import main
  File "/usr/local/lib/python2.7/dist-packages/kipart/__main__.py", line 31, in <module>
    from .kipart import *
  File "/usr/local/lib/python2.7/dist-packages/kipart/kipart.py", line 27, in <module>
    from builtins import str
ImportError: No module named builtins

**Comment by xesscorp** [comment]
fixed #2 by adding future module to list of requirements in setup.py
