### ISSUE TITLE
Tool crashes for unknown reason

### ISSUE THREAD

**Issue by trcwm** [xesscorp/KiPart#21]
System: windows 10, latest github version.

Error report:
"E:\Programming\HD6309_computer\documentation>kipart iCE40PinoutHX1K_kiparts2.csv --overwrite
Traceback (most recent call last):
  File "C:\Python35\Scripts\kipart-script.py", line 11, in <module>
    load_entry_point('kipart==0.1.24', 'console_scripts', 'kipart')()
  File "c:\python35\lib\site-packages\kipart-0.1.24-py3.5.egg\kipart\__main__.py", line 144, in main
    append_to_lib = call_kipart(part_data_file)
  File "c:\python35\lib\site-packages\kipart-0.1.24-py3.5.egg\kipart\__main__.py", line 127, in call_kipart
    debug_level=args.debug)
  File "c:\python35\lib\site-packages\kipart-0.1.24-py3.5.egg\kipart\kipart.py", line 679, in kipart
    fuzzy_match=fuzzy_match)
  File "c:\python35\lib\site-packages\kipart-0.1.24-py3.5.egg\kipart\kipart.py", line 507, in draw_symbol
    balance_bboxes(bbox)
  File "c:\python35\lib\site-packages\kipart-0.1.24-py3.5.egg\kipart\kipart.py", line 281, in balance_bboxes
    lr_bbox = find_bbox_bbox(bboxes['left'], bboxes['right'])
KeyError: 'left'"

CSV file:
[iCE40PinoutHX1K_kiparts2.zip](https://github.com/xesscorp/KiPart/files/877054/iCE40PinoutHX1K_kiparts2.zip)

**Comment by xesscorp** [comment]
Thanks for the bug report and the test file. The problem was caused by using pin side designators like 'Left' instead of 'left'. The generic part reader now lower-cases the side designator upon reading in the CSV file.
